"""init

Revision ID: 1683f2f65f57
Revises:     
Created:     2026-07-31
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1683f2f65f57'
down_revision: str | None = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_snowflake', sa.BigInteger(), nullable=True),
    sa.Column('role_name', sa.Text(), nullable=False),
    sa.Column('acronym', sa.Text(), nullable=False),
    sa.Column('sort_index', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('snowflake', sa.BigInteger(), nullable=False),
    sa.Column('roblox_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('snowflake')
    )
    op.create_table('season',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('is_playoffs', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_snowflake', sa.BigInteger(), nullable=True),
    sa.Column('role_name', sa.Text(), nullable=False),
    sa.Column('division', sa.Integer(), nullable=True),
    sa.Column('subdivision', sa.Integer(), nullable=True),
    sa.Column('gsp', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('award',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('role_snowflake', sa.BigInteger(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_snowflake', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('length_type', sa.Integer(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('terminated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('termination_justification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_snowflake'], ['player.snowflake'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contract_player_active', 'contract', ['player_snowflake', 'is_active'], unique=False)
    op.create_index('idx_contract_team', 'contract', ['team_id'], unique=False)
    op.create_table('game',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=False),
    sa.Column('home_team_id', sa.BigInteger(), nullable=True),
    sa.Column('away_team_id', sa.BigInteger(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('is_forfeit', sa.Boolean(), nullable=False),
    sa.Column('is_double_forfeit', sa.Boolean(), nullable=False),
    sa.Column('forfeit_by_home', sa.Boolean(), nullable=True),
    sa.Column('forfeit_by_away', sa.Boolean(), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('division', sa.Integer(), nullable=True),
    sa.Column('subdivision', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('scheduled_for', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('thread_snowflake', sa.BigInteger(), nullable=False),
    sa.Column('referee_snowflakes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('streamers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reporter_snowflake', sa.BigInteger(), nullable=False),
    sa.Column('reported_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('approver_snowflake', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_snowflake'], ['player.snowflake'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_snowflake'], ['player.snowflake'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_game_away_team', 'game', ['away_team_id'], unique=False)
    op.create_index('idx_game_home_team', 'game', ['home_team_id'], unique=False)
    op.create_index('idx_game_season', 'game', ['season_id'], unique=False)
    op.create_index('idx_game_season_away', 'game', ['season_id', 'away_team_id'], unique=False)
    op.create_index('idx_game_season_home', 'game', ['season_id', 'home_team_id'], unique=False)
    op.create_table('player_sanction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_snowflake', sa.BigInteger(), nullable=False),
    sa.Column('sanction_type', sa.Integer(), nullable=False),
    sa.Column('moderator_snowflake', sa.BigInteger(), nullable=True),
    sa.Column('sanctioned_until', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sanctioned_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('justification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('banned_until', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['moderator_snowflake'], ['player.snowflake'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_snowflake'], ['player.snowflake'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sanction_active', 'player_sanction', ['is_active'], unique=False)
    op.create_index('idx_sanction_player_type', 'player_sanction', ['player_snowflake', 'sanction_type'], unique=False)
    op.create_index('idx_sanction_type_active', 'player_sanction', ['sanction_type', 'is_active'], unique=False)
    op.create_table('team_owner_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_snowflake', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('appointed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('unappointed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_snowflake'], ['player.snowflake'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_season_stage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('division', sa.Integer(), nullable=True),
    sa.Column('subdivision', sa.Text(), nullable=True),
    sa.Column('gsp', sa.Integer(), nullable=True),
    sa.Column('is_play_in', sa.Boolean(), nullable=True),
    sa.Column('is_auto_qualified', sa.Boolean(), nullable=True),
    sa.Column('is_champion', sa.Boolean(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'team_id', 'stage', name='idx_season_team_unique')
    )
    op.create_index('idx_season_team_stage', 'team_season_stage', ['season_id', 'stage'], unique=False)
    op.create_index('idx_season_team_team', 'team_season_stage', ['team_id'], unique=False)
    op.create_table('award_assignment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('award_id', sa.BigInteger(), nullable=False),
    sa.Column('player_snowflake', sa.BigInteger(), nullable=True),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['award.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_snowflake'], ['player.snowflake'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_award_assign_award', 'award_assignment', ['award_id'], unique=False)
    op.create_index('idx_award_assign_player', 'award_assignment', ['player_snowflake'], unique=False)
    op.create_index('idx_award_assign_team', 'award_assignment', ['team_id'], unique=False)
    op.create_index('idx_award_assign_unique_player', 'award_assignment', ['award_id', 'player_snowflake'], unique=True, postgresql_where=sa.text('player_snowflake IS NOT NULL'))
    op.create_index('idx_award_assign_unique_team', 'award_assignment', ['award_id', 'team_id'], unique=True, postgresql_where=sa.text('team_id IS NOT NULL'))
    op.create_table('player_stat',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=True),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('roblox_id', sa.BigInteger(), nullable=False),
    sa.Column('player_snowflake', sa.BigInteger(), nullable=True),
    sa.Column('quarterback', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rushing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('receiver', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('corner', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('defender', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kicker', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_snowflake'], ['player.snowflake'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_player_stat_box_score', 'player_stat', ['game_id', 'team_id', 'roblox_id'], unique=False)
    op.create_index('idx_player_stat_roblox', 'player_stat', ['roblox_id'], unique=False)
    op.create_index('idx_player_stat_season', 'player_stat', ['season_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_player_stat_season', table_name='player_stat')
    op.drop_index('idx_player_stat_roblox', table_name='player_stat')
    op.drop_index('idx_player_stat_box_score', table_name='player_stat')
    op.drop_table('player_stat')
    op.drop_index('idx_award_assign_unique_team', table_name='award_assignment', postgresql_where=sa.text('team_id IS NOT NULL'))
    op.drop_index('idx_award_assign_unique_player', table_name='award_assignment', postgresql_where=sa.text('player_snowflake IS NOT NULL'))
    op.drop_index('idx_award_assign_team', table_name='award_assignment')
    op.drop_index('idx_award_assign_player', table_name='award_assignment')
    op.drop_index('idx_award_assign_award', table_name='award_assignment')
    op.drop_table('award_assignment')
    op.drop_index('idx_season_team_team', table_name='team_season_stage')
    op.drop_index('idx_season_team_stage', table_name='team_season_stage')
    op.drop_table('team_season_stage')
    op.drop_table('team_owner_history')
    op.drop_index('idx_sanction_type_active', table_name='player_sanction')
    op.drop_index('idx_sanction_player_type', table_name='player_sanction')
    op.drop_index('idx_sanction_active', table_name='player_sanction')
    op.drop_table('player_sanction')
    op.drop_index('idx_game_season_home', table_name='game')
    op.drop_index('idx_game_season_away', table_name='game')
    op.drop_index('idx_game_season', table_name='game')
    op.drop_index('idx_game_home_team', table_name='game')
    op.drop_index('idx_game_away_team', table_name='game')
    op.drop_table('game')
    op.drop_index('idx_contract_team', table_name='contract')
    op.drop_index('idx_contract_player_active', table_name='contract')
    op.drop_table('contract')
    op.drop_table('award')
    op.drop_table('team')
    op.drop_table('season')
    op.drop_table('player')
    op.drop_table('coach')
    # ### end Alembic commands ###